# Generated by Django 5.1.2 on 2025-01-12 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facebook", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="facebookpost",
            old_name="title",
            new_name="message",
        ),
        migrations.DeleteModel(
            name="FacebookComment",
        ),
    ]
